"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!qrj__ihk0s!#0y#qtple*lcv@&ci7^(c4mgw(_ht__am6&we("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "relationship_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Add your new CSP middleware here (use your actual app name)
    "bookshelf.middleware.ContentSecurityPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
]

ROOT_URLCONF = "LibraryProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "LibraryProject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Redirect to the books list (or any name from your urls.py) after login
LOGIN_REDIRECT_URL = "list_books"

# Redirect to the login page after logging out
LOGOUT_REDIRECT_URL = "login"

AUTH_USER_MODEL = "bookshelf.CustomUser"

# 1. Production Security Settings
# IMPORTANT: In a real production environment, this must be False.
# However, for local testing, if you set this to False, you MUST set ALLOWED_HOSTS = ['127.0.0.1']
DEBUG = False
ALLOWED_HOSTS = ["*"]  # Required when DEBUG is False

# 2. Browser-Side Protections
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"  # Prevents Clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True

# 3. Secure Cookies (HTTPS only)
# Note: If you are running locally without HTTPS (http://127.0.0.1),
# these next two lines might break your login.
# Set them to True only if you have HTTPS set up or are deploying.
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True


# --- STEP 1: Configure HTTPS Support ---

# Redirects all non-HTTPS requests to HTTPS (http:// -> https://)
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS) settings
# Tells the browser: "For the next 1 year, ONLY talk to me over HTTPS."
SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True


# --- STEP 2: Enforce Secure Cookies ---

# Prevents the session cookie from being sent over unencrypted connections
SESSION_COOKIE_SECURE = True

# Prevents the CSRF token from being sent over unencrypted connections
CSRF_COOKIE_SECURE = True


# --- STEP 3: Implement Secure Headers ---

# Prevents the browser from MIME-sniffing a response away from the declared content-type
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enables the browser's XSS filtering and helps prevent cross-site scripting attacks
SECURE_BROWSER_XSS_FILTER = True

# Prevents your site from being embedded in frames (protects against Clickjacking)
X_FRAME_OPTIONS = "DENY"
